const source=document.querySelector('#source'), sourceLang=document.querySelector('#sourceLang'), target=document.querySelector('#target'), button=document.querySelector('#translate');
const langs={en:'英语 · 美国',de:'德语 · 德国',fr:'法语 · 法国',es:'西班牙语 · 西班牙',ja:'日语 · 日本',ko:'韩语 · 韩国',it:'意大利语 · 意大利',pt:'葡萄牙语 · 巴西'};
const notes={en:'已转换为自然的北美商品文案。发布前请确认品牌词、尺寸单位与平台禁用词。',de:'德语商品页通常重视规格清晰度。发布前请核对技术参数与合规声明。',ja:'日语消费者偏好克制、准确的表达。发布前请核对敬语、型号与尺寸。',default:'已按目标市场生成自然表达，请在发布前核对尺寸、材质及合规信息。'};
source.addEventListener('input',()=>document.querySelector('#count').textContent=source.value.length);
function useTemplate(text){source.value=text;source.dispatchEvent(new Event('input'));source.focus();source.scrollIntoView({behavior:'smooth',block:'center'})}
document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>useTemplate(b.dataset.text));
document.querySelectorAll('.trend-card').forEach(b=>b.onclick=()=>useTemplate(b.dataset.text));
const scanModal=document.querySelector('#scanModal');
document.querySelector('#scanOpen').onclick=()=>scanModal.hidden=false;
[document.querySelector('#scanClose'),document.querySelector('#scanCloseIcon')].forEach(el=>el.onclick=()=>scanModal.hidden=true);
document.querySelectorAll('#tone button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tone button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function chunks(text){const parts=text.match(/[^\n。！？.!?]+[\n。！？.!?]*/g)||[text],out=[];let current='';for(const part of parts){if((current+part).length>420&&current){out.push(current);current=part}else current+=part}if(current)out.push(current);return out}
async function translate(){const text=source.value.trim();if(!text)return source.focus();if(sourceLang.value===target.value){document.querySelector('#translation').textContent='原文语言与目标市场相同，请选择不同的目标市场。';document.querySelector('#empty').hidden=true;document.querySelector('#result').hidden=false;document.querySelector('#status').textContent='需要调整';return}button.disabled=true;button.querySelector('span').textContent='正在本地化…';document.querySelector('#status').textContent='处理中';try{const result=await Promise.all(chunks(text).map(async part=>{const url='https://api.mymemory.translated.net/get?q='+encodeURIComponent(part)+'&langpair='+sourceLang.value+'|'+target.value;const res=await fetch(url);const data=await res.json();if(!data.responseData?.translatedText)throw Error();return data.responseData.translatedText.replace(/&quot;/g,'"').replace(/&#39;/g,"'")}));const out=result.join('');document.querySelector('#translation').textContent=out;document.querySelector('#langLabel').textContent=langs[target.value];document.querySelector('#localNote').textContent=notes[target.value]||notes.default;document.querySelector('#empty').hidden=true;document.querySelector('#result').hidden=false;document.querySelector('#copy').disabled=false;document.querySelector('#status').textContent='已完成'}catch(e){document.querySelector('#translation').textContent='翻译服务暂时无法连接。请检查网络后重试，或稍后再试。';document.querySelector('#empty').hidden=true;document.querySelector('#result').hidden=false;document.querySelector('#status').textContent='请求失败'}finally{button.disabled=false;button.querySelector('span').textContent='翻译并本地化'}}
button.onclick=translate;document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')translate()});
document.querySelector('#copy').onclick=async()=>{const value=document.querySelector('#translation').textContent;try{await navigator.clipboard.writeText(value)}catch{const area=document.createElement('textarea');area.value=value;document.body.append(area);area.select();document.execCommand('copy');area.remove()}const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)};
